var wind_width=window.innerWidth;
if(wind_width<370){
    changingSlideTime=800;
}
else{
    changingSlideTime=2000;
}

function navProgress3(sN){
    var len = document.getElementsByClassName("productBox").length;
    var ans=(sN*100)/len;
    document.getElementById("navProgress3").style.width=ans+"%";
}
navProgress3(slide4counter);

function nextProduct(){
    var tempSlide4Num=slide4counter+1;
    navProgress3(tempSlide4Num);
    if(slide4counter==1){
        document.getElementById("productBox").classList.add("customProductBox");

        setTimeout(()=>{
            document.getElementById("productBox2").classList.remove("customProductBox");
            document.getElementById("productBox").classList.remove("activeOwn");
            document.getElementById("productBox2").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=2;
        document.getElementById("prev-btn-txt3").innerText="prev";
        return;
    }
    if(slide4counter==2){
        document.getElementById("productBox2").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox3").classList.remove("customProductBox");
            document.getElementById("productBox2").classList.remove("activeOwn");
            document.getElementById("productBox3").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=3;
        return;
    }
    if(slide4counter==3){
        document.getElementById("productBox3").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox4").classList.remove("customProductBox");
            document.getElementById("productBox3").classList.remove("activeOwn");
            document.getElementById("productBox4").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=4;
        return;
    }
    if(slide4counter==4){
        document.getElementById("productBox4").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox5").classList.remove("customProductBox");
            document.getElementById("productBox4").classList.remove("activeOwn");
            document.getElementById("productBox5").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=5;
        return;
    }
    if(slide4counter==5){
        document.getElementById("productBox5").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox6").classList.remove("customProductBox");
            document.getElementById("productBox5").classList.remove("activeOwn");
            document.getElementById("productBox6").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=6;
        return;
    }
    if(slide4counter==6){
        document.getElementById("productBox6").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox7").classList.remove("customProductBox");
            document.getElementById("productBox6").classList.remove("activeOwn");
            document.getElementById("productBox7").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=7;
        return;
    }
    if(slide4counter==7){
        document.getElementById("productBox7").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox8").classList.remove("customProductBox");
            document.getElementById("productBox7").classList.remove("activeOwn");
            document.getElementById("productBox8").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=8;
        return;
    }
    if(slide4counter==8){
        document.getElementById("productBox8").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox9").classList.remove("customProductBox");
            document.getElementById("productBox8").classList.remove("activeOwn");
            document.getElementById("productBox9").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=9;
        document.getElementById("next-product").innerText="Home";
        return;
    }
    if(slide4counter==9){
        showIntro()
    }
    
}

function prevProduct(){
    var tempSlide4Num=slide4counter-1;
    navProgress3(tempSlide4Num);
    if(slide4counter==1){
        showOcean();
    }
    if(slide4counter==2){
        document.getElementById("productBox2").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox").classList.remove("customProductBox");
            document.getElementById("productBox2").classList.remove("activeOwn");
            document.getElementById("productBox").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=1;
        document.getElementById("prev-btn-txt3").innerText="prev page";
        return;
    }
    if(slide4counter==3){
        document.getElementById("productBox3").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox2").classList.remove("customProductBox");
            document.getElementById("productBox3").classList.remove("activeOwn");
            document.getElementById("productBox2").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=2;
        return;
    }
    if(slide4counter==4){
        document.getElementById("productBox4").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox3").classList.remove("customProductBox");
            document.getElementById("productBox4").classList.remove("activeOwn");
            document.getElementById("productBox3").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=3;
        return;
    }
    if(slide4counter==5){
        document.getElementById("productBox5").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox4").classList.remove("customProductBox");
            document.getElementById("productBox5").classList.remove("activeOwn");
            document.getElementById("productBox4").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=4;
        return;
    }
    if(slide4counter==6){
        document.getElementById("productBox6").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox5").classList.remove("customProductBox");
            document.getElementById("productBox6").classList.remove("activeOwn");
            document.getElementById("productBox5").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=5;
        return;
    }
    if(slide4counter==7){
        document.getElementById("productBox7").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox6").classList.remove("customProductBox");
            document.getElementById("productBox7").classList.remove("activeOwn");
            document.getElementById("productBox6").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=6;
        return;
    }
    if(slide4counter==8){
        document.getElementById("productBox8").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox7").classList.remove("customProductBox");
            document.getElementById("productBox8").classList.remove("activeOwn");
            document.getElementById("productBox7").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=7;
        return;
    }
    if(slide4counter==9){
        document.getElementById("productBox9").classList.add("customProductBox");
        setTimeout(()=>{
            document.getElementById("productBox8").classList.remove("customProductBox");
            document.getElementById("productBox9").classList.remove("activeOwn");
            document.getElementById("productBox8").classList.add("activeOwn");
        },changingSlideTime)
        slide4counter=8;
        document.getElementById("next-product").style.display="block";
        document.getElementById("next-product").innerText="Next";
        return;
    }
}